# Generated by Django 4.0.1 on 2022-02-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_discounted_price_product_actual_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
