# Generated by Django 4.0.1 on 2022-02-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BT', 'Bottom Wear'), ('S', 'Shoes'), ('BEA', 'Beauty Product'), ('CO', 'Coffee'), ('GRO', 'Grocery')], max_length=5),
        ),
    ]
