# Generated by Django 4.0.1 on 2022-02-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_discription',
        ),
    ]
